spring:
  data:
    redis:
      host: localhost
      port: 6379

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESSKEY}
      secret-key: ${AWS_SECRETKEY}
    region:
      static: ${AWS_REGION}
      auto: false
    stack:
      auto: false
    sqs:
      queue:
        name: ${AWS_SQS_NAME}
        url: ${AWS_SQS_URL}